local:
  buckets: 
    inputs: '../../data/dof-simulation/inputs'
    inputs_dest: '../../data/dof-simulation/inputs-dest'
    objectives: '../../data/dof-simulation/objectives'
    objectives_dest: '../../data/dof-simulation/objectives-dest'
    data: '../../data/dof-simulation/data'
    data_dest: '../../data/dof-simulation/data-dest'
    solutions: '../../data/dof-simulation/solutions'